export enum LoginPros{
    DO_LOGIN = 'DO_LOGIN',
    ERROR_VALIDE = 'ERROR_VALIDE',
    LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER',
    LOGIN_SUCCESS_ADMIN = 'LOGIN_SUCCESS_ADMIN',
    LOGIN_ERROR = 'LOGIN_ERROR'
}


