export enum RPr{
    DO_REGISTER = 'DO_REGISTER',
    ADD_USER = 'ADD_USER',
    SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION',
    USER_EXSIST = 'USER_EXSIST',
    ERROR_REGISTRATION = 'ERROR_REGISTRATION'
}
export enum valReg{
    ERROR_VALIDE = 'ERROR_VALIDE'
}


